import { detectRuntime, detectMode, getEnvar } from "js_utils/environment";

const RUNTIME = detectRuntime();
const MODE = detectMode();
const LOGLEVEL = getEnvar("LOGLEVEL", false, "trace");
const CACHEDIR = getEnvar("CACHEDIR", false, "/tmp");
const CONFDIR = getEnvar("CONFDIR", false);

// Clickup credentials
const CLICKUP_LOGIN_USERNAME = getEnvar("CLICKUP_LOGIN_USERNAME", true);
const CLICKUP_LOGIN_PASS = getEnvar("CLICKUP_LOGIN_PASS", true);
const CLICKUP_LOGIN_AUTH_TOKEN = getEnvar("CLICKUP_LOGIN_AUTH_TOKEN", true);

// clickpie - server, servicing both UI clients and API clients
// public url
const CLICKPIE_SERVER_URL_PUBLIC_SCHEME = getEnvar(
  "CLICKUP_SERVER_URL_PUBLIC_SCHEME",
  true,
);
const CLICKPIE_SERVER_URL_PUBLIC_PORT = getEnvar(
  "CLICKUP_SERVER_URL_PUBLIC_PORT",
  true,
);
const CLICKPIE_SERVER_URL_PUBLIC_HOSTNAME = getEnvar(
  "CLICKUP_SERVER_URL_PUBLIC_HOSTNAME",
  true,
);
// local url
const CLICKPIE_SERVER_URL_LOCAL_SCHEME = getEnvar(
  "CLICKPIE_SERVER_URL_LOCAL_SCHEME",
  true,
);
const CLICKPIE_SERVER_URL_LOCAL_PORT = getEnvar(
  "CLICKPIE_SERVER_URL_LOCAL_PORT",
  true,
);
const CLICKPIE_SERVER_URL_LOCAL_HOSTNAME = getEnvar(
  "CLICKPIE_SERVER_URL_LOCAL_HOSTNAME",
  true,
);
// # clickpie - api, serviced by clickpie - server
// # public url
const CLICKPIE_API_URL_PUBLIC_SCHEME = getEnvar(
  "CLICKPIE_API_URL_PUBLIC_SCHEME",
  true,
);
const CLICKPIE_API_URL_PUBLIC_PORT = getEnvar(
  "CLICKPIE_API_URL_PUBLIC_PORT",
  true,
);
const CLICKPIE_API_URL_PUBLIC_HOSTNAME = getEnvar(
  "CLICKPIE_API_URL_PUBLIC_HOSTNAME",
  true,
);
const CLICKPIE_API_URL_PUBLIC = getEnvar("CLICKPIE_API_URL_PUBLIC", true);
// # local url
const CLICKPIE_API_URL_LOCAL_SCHEME = getEnvar(
  "CLICKPIE_API_URL_LOCAL_SCHEME",
  true,
);
const CLICKPIE_API_URL_LOCAL_PORT = getEnvar(
  "CLICKPIE_API_URL_LOCAL_PORT",
  true,
);
const CLICKPIE_API_URL_LOCAL_HOSTNAME = getEnvar(
  "CLICKPIE_API_URL_LOCAL_HOSTNAME",
  true,
);
const CLICKPIE_API_URL_LOCAL = getEnvar("CLICKPIE_API_URL_LOCAL", true);

export {
  CACHEDIR,
  MODE,
  RUNTIME,
  CLICKPIE_API_URL_LOCAL_HOSTNAME,
  CLICKPIE_API_URL_LOCAL_PORT,
  CLICKPIE_API_URL_LOCAL_SCHEME,
  CLICKPIE_API_URL_LOCAL_URL,
  CLICKPIE_API_URL_PUBLIC_HOSTNAME,
  CLICKPIE_API_URL_PUBLIC_PORT,
  CLICKPIE_API_URL_PUBLIC_SCHEME,
  CLICKPIE_API_URL_PUBLIC_URL,
  CLICKPIE_SERVER_URL_LOCAL_HOSTNAME,
  CLICKPIE_SERVER_URL_LOCAL,
  CLICKPIE_SERVER_URL_LOCAL_PORT,
  CLICKPIE_SERVER_URL_LOCAL_SCHEME,
  CLICKPIE_SERVER_URL_PUBLIC_HOSTNAME,
  CLICKPIE_SERVER_URL_PUBLIC,
  CLICKPIE_SERVER_URL_PUBLIC_PORT,
  CLICKPIE_SERVER_URL_PUBLIC_SCHEME,
  CLICKUP_LOGIN_AUTH_TOKEN,
  CLICKUP_LOGIN_PASS,
  CLICKUP_LOGIN_USERNAME,
  CONFDIR,
  LOGLEVEL,
};
